### ISSUE TITLE
Adicionar Obras

### ISSUE THREAD

**Issue by MF853** [pedroph99/express_fullstack_project#2]
* Criar função para receber requisição http e salvar nova obra na pasta fake_db.

* Caminho onde o arquivo deve ser salvo:
~~~
/fake_db/project_info
~~~

* Rota HTTP:
~~~
/adicionar-obra
~~~

**Comment by pedroph99** [comment]
O express.js utiliza diversas bibliotecas separadas para auxiliar no desenvolvimento da lógica do servidor e das requisições. No campo das requisições, usamos neste projeto o Formidable(), uma biblioteca utilizada para tratar formulários nas requisições HTTP(form-data).  Usando formidable, ao invés de passar req.body, temos que passar os posts através de um form-data com sua respectiva key e value e acessá-los não pelo req.body mas sim por req.fields. A falta de conhecimento dessa funcionalidade resultou em várias horas presos em um bug. Usando a estrutura de form-data, foi possível fazer a req tanto pelo AXIOS e pelo POSTMAN.
